-- 사용자 시퀀스
CREATE SEQUENCE SEQ_CTUSER;


-- 숙소 관련 시퀀스
CREATE SEQUENCE SEQ_ACCOM;
CREATE SEQUENCE SEQ_ACCOM_DETAIL;
CREATE SEQUENCE SEQ_ACCOM_CATE;

CREATE SEQUENCE SEQ_REGION;
CREATE SEQUENCE SEQ_ACCOM_IMAGE;

-- 관광지 시퀀스
CREATE SEQUENCE SEQ_ATTRACTION;

-- 예약 관련 시퀀스
CREATE SEQUENCE SEQ_ACCOM_RESERV;


-- 결제/리뷰
CREATE SEQUENCE SEQ_ACCOM_REVIEW;
CREATE SEQUENCE SEQ_PAYMENT;

-- 찜/신고
CREATE SEQUENCE SEQ_WISHLIST;
CREATE SEQUENCE SEQ_ACCOM_REPORT;

-- 채팅
CREATE SEQUENCE SEQ_CHATROOM;
CREATE SEQUENCE SEQ_CHAT_MESSAGE;
CREATE SEQUENCE SEQ_CHAT_MEMBER;


-- 알림/프로모션
CREATE SEQUENCE SEQ_NOTIFICATION;
CREATE SEQUENCE SEQ_PROMOTION;

-- 문의/답변
CREATE SEQUENCE SEQ_INQUIRY;
CREATE SEQUENCE SEQ_ANSWER;

-- 여행 그룹
CREATE SEQUENCE SEQ_TRAVELGROUP;
CREATE SEQUENCE SEQ_GROUP_MEMBER;